// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValuationUIClient is the client API for ValuationUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValuationUIClient interface {
	// ListEngineSpecs returns a list of Valuation Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ValuationUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type valuationUIClient struct {
	cc grpc.ClientConnInterface
}

func NewValuationUIClient(cc grpc.ClientConnInterface) ValuationUIClient {
	return &valuationUIClient{cc}
}

func (c *valuationUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ValuationUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ValuationUI_ServiceDesc.Streams[0], "/v1.ValuationUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &valuationUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ValuationUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type valuationUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *valuationUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *valuationUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ValuationUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValuationUIServer is the server API for ValuationUI service.
// All implementations must embed UnimplementedValuationUIServer
// for forward compatibility
type ValuationUIServer interface {
	// ListEngineSpecs returns a list of Valuation Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ValuationUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedValuationUIServer()
}

// UnimplementedValuationUIServer must be embedded to have forward compatible implementations.
type UnimplementedValuationUIServer struct {
}

func (UnimplementedValuationUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ValuationUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedValuationUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedValuationUIServer) mustEmbedUnimplementedValuationUIServer() {}

// UnsafeValuationUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValuationUIServer will
// result in compilation errors.
type UnsafeValuationUIServer interface {
	mustEmbedUnimplementedValuationUIServer()
}

func RegisterValuationUIServer(s grpc.ServiceRegistrar, srv ValuationUIServer) {
	s.RegisterService(&ValuationUI_ServiceDesc, srv)
}

func _ValuationUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ValuationUIServer).ListEngineSpecs(m, &valuationUIListEngineSpecsServer{stream})
}

type ValuationUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type valuationUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *valuationUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ValuationUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValuationUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ValuationUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValuationUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValuationUI_ServiceDesc is the grpc.ServiceDesc for ValuationUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValuationUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ValuationUI",
	HandlerType: (*ValuationUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ValuationUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ValuationUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "valuation-ui.proto",
}
